### create report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "ford",
    "model": "mustang",
    "year": 1982,
    "mileage": 100000,
    "lat": 0,
    "lng": 0,
    "price": 20000
}

### approve report
PATCH http://localhost:3000/reports/4
Content-Type: application/json

{
    "approved": true
}

### get estimate price for existing vehicle
GET http://localhost:3000/reports?make=ford&model=mustang&lat=0&lng=0&mileage=100000&year=1980